# Generated by Django 5.2 on 2026-06-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_create_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoria de Compra",
                "verbose_name_plural": "Categorias de Compra",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Requisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=500)),
                (
                    "valor_estimado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("justificativa", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PENDENTE_GESTOR", "Aguardando Gestor"),
                            ("PENDENTE_DIRETOR", "Aguardando Diretor"),
                            ("APROVADO", "Aprovado"),
                            ("REPROVADO", "Reprovado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisicoes",
                        to="requisicoes.categoriacompra",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisicoes",
                        to="accounts.unidadeorganizacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de Compra",
                "verbose_name_plural": "Requisições de Compra",
                "ordering": ["-criado_em"],
            },
        ),
    ]
