# Generated by Django 5.2 on 2026-06-11 20:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0002_remove_fornecedor_fornecedor_ativo_idx_and_more'),
        ('requisicoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prazo_entrega', models.CharField(blank=True, default='', max_length=100)),
                ('condicoes_pagamento', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Cotacao de Fornecedor',
                'verbose_name_plural': 'Cotacoes de Fornecedores',
                'ordering': ['preco_unitario'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('justificativa_selecao', models.TextField(blank=True, default='')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_criados', to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rfq', to='requisicoes.requisicao')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_vencidos', to='cotacoes.cotacaofornecedor')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='cotacoes.rfq'),
        ),
    ]
