# Generated by Django 5.2 on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    CR-02: altera on_delete de RFQ.vencedor de SET_NULL para PROTECT.
    Garante imutabilidade do vencedor (D-07): deleção de CotacaoFornecedor
    vencedora levanta ProtectedError em vez de silenciosamente reverter o RFQ
    para "Em andamento".
    """

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='vencedor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='rfqs_vencidos',
                to='cotacoes.cotacaofornecedor',
            ),
        ),
    ]
