# Generated by Django 5.2 on 2026-06-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requisicoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoAlcada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_maximo_gestor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text=(
                            "Valor máximo para aprovação apenas pelo Gestor (R$). "
                            "Acima deste valor, exige aprovação do Diretor também. "
                            "Deixe em branco para sempre exigir 2 níveis (comportamento seguro)."
                        ),
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Alçada",
                "verbose_name_plural": "Configuração de Alçada",
            },
        ),
        migrations.CreateModel(
            name="AprovacaoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("ENVIO", "Envio para Aprovação"),
                            ("APROVACAO_GESTOR", "Aprovação pelo Gestor"),
                            ("APROVACAO_FINAL", "Aprovação Final"),
                            ("REPROVACAO", "Reprovação"),
                            ("CANCELAMENTO", "Cancelamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField(blank=True, default="")),
                (
                    "aprovador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="requisicoes.requisicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Aprovação",
                "verbose_name_plural": "Logs de Aprovação",
                "ordering": ["criado_em"],
            },
        ),
    ]
