# Generated by Django 6.0.6 on 2026-06-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedor_ativo_idx',
        ),
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedor_categoria_idx',
        ),
    ]
